- homeworks/darya-shimanskaya/02-git/README.md
> [homework #2] -Markdown CV by Darya Shimanskaya

- homeworks/roman-ivashkevich/01-basics/README.md
- homeworks/roman-ivashkevich/02-git/README.md
> [homework #2] - Markdown CV by Roman Ivashkevich

- homeworks/darya-shimanskaya/03-html-css/CV/cv.css
- homeworks/darya-shimanskaya/03-html-css/CV/cv.html
- homeworks/darya-shimanskaya/03-html-css/Floats/floats.css
- homeworks/darya-shimanskaya/03-html-css/Floats/floats.html
> [homework#3] HTML-CSS by Darya Shimanskaya

- homeworks/ivan-poberezhniuk/03-html-css/1-float-inline/index.html
- homeworks/ivan-poberezhniuk/03-html-css/1-float-inline/styles/styles.css
- homeworks/ivan-poberezhniuk/03-html-css/1-float-inline/styles/variables.css
- homeworks/ivan-poberezhniuk/03-html-css/2-cv/index.html
- homeworks/ivan-poberezhniuk/03-html-css/2-cv/styles/aside.css
- homeworks/ivan-poberezhniuk/03-html-css/2-cv/styles/header.css
- homeworks/ivan-poberezhniuk/03-html-css/2-cv/styles/main.css
- homeworks/ivan-poberezhniuk/03-html-css/2-cv/styles/styles.css
- homeworks/ivan-poberezhniuk/03-html-css/2-cv/styles/variables.css
> [homework#3] HTML-CSS-CV by Ivan Poberezhniuk

- homeworks/ruslan-potreba/02-git/README.md
Just a common pull request here. CV screenshot is attached.
> [homework #2] - Markdown CV by Ruslan Potreba

- homeworks/inna-smiiun/02-git/README.md
> [homework #2] - Markdown CV by Inna Smiiun

- homeworks/igor-ignatenko/03-html-css/task 1/index.html
- homeworks/igor-ignatenko/03-html-css/task 1/style.css
- homeworks/igor-ignatenko/03-html-css/task 2/index.html
- homeworks/igor-ignatenko/03-html-css/task 2/style.css
> [homework#3] HTML-CSS by Igor Ignatenko

- homeworks/ivan-poberezhniuk/.eslintrc.json
- homeworks/ivan-poberezhniuk/.prettierrc
- homeworks/ivan-poberezhniuk/06-js-basic/index.js
- homeworks/ivan-poberezhniuk/package-lock.json
- homeworks/ivan-poberezhniuk/package.json
> [homework#6]-js-basics by Ivan Poberezhniuk

- homeworks/ivan-poberezhniuk/06-js-basic/index.js
- homeworks/ivan-poberezhniuk/07-js-basic/index.js
> [homework#7]-js-basics by Ivan Poberezhniuk

- homeworks/ruslan-potreba/06-js-basics-1/.eslintrc.json
- homeworks/ruslan-potreba/06-js-basics-1/.prettierrc.json
- homeworks/ruslan-potreba/06-js-basics-1/index.js
- homeworks/ruslan-potreba/06-js-basics-1/package-lock.json
- homeworks/ruslan-potreba/06-js-basics-1/package.json
> [homework#6]-js-basics by Ruslan Potreba

- homeworks/roman-palagniuk/08-js-part-3/index.js
> [homework#8] Js-part-3 by Roman Palagniuk

- homeworks/ivan-poberezhniuk/09-js-part-4/index.js
Implemented serializatioin and deserialization of objects
> [homework#9]-js-part-4 by Ivan Poberezhniuk

- homeworks/roman-palagniuk/09-js-part-4/indexNine.js
had some issues with this task. it's not finished at all. hope to understand it better before exam
> [homework#9] JS-part-4 by Roman Palagniuk

- homeworks/ruslan-potreba/07-js-basics/index.js
> [homework#7]-js-basics by Ruslan Potreba

- homeworks/ruslan-potreba/08-js-basics-3/index.html
- homeworks/ruslan-potreba/08-js-basics-3/index.js
> [homework#8]-js-part-3 by Ruslan Potreba

- homeworks/roman-palagniuk/10-js-part-5/10index.js
- homeworks/roman-palagniuk/10-js-part-5/10task5.html
- homeworks/roman-palagniuk/10-js-part-5/10task5.js
- homeworks/roman-palagniuk/10-js-part-5/index10.html
> [homework#10] JS-part-5 by Roman Palagniuk

- homeworks/vitalina-poremchuk/10-js/index.html
- homeworks/vitalina-poremchuk/10-js/script.js
- homeworks/vitalina-poremchuk/10-js/style.css
> [homework#10]-js-basics by Vitalina Poremchuk

- homeworks/igor-ignatenko/10-js-part5/index.html
- homeworks/igor-ignatenko/10-js-part5/script.js
- homeworks/igor-ignatenko/10-js-part5/style.css
> [homework#10] JS-part-5 by Igor Ignatenko

- homeworks/daria-movchan/06-js-basic/index.js
- homeworks/daria-movchan/07-js-basic/index.js
> [homework#7]-js-basics by Movchan Daria

- homeworks/karina-akulenok/11-js-part-6/index.html
- homeworks/karina-akulenok/11-js-part-6/script.js
- homeworks/karina-akulenok/11-js-part-6/style.css
> [homework#11]-js-part-6 by Karina Akulenok

- homeworks/ruslan-potreba/10-js-part-5/index.css
- homeworks/ruslan-potreba/10-js-part-5/index.html
- homeworks/ruslan-potreba/10-js-part-5/index.js
All of the practical tasks are done.
> [homework#10]-js-part-5 by Ruslan Potreba
